version: '3.8'

services:

  db:
    container_name: postgres_db_ct
    image: postgres:latest
    # restart: always
    volumes:
      - db_value:/var/lib/postgresql/data/
    env_file:
       - .env.docker
#      - ../.env
#    environment: or .env file to load params
#      POSTGRES_USER: user
#      POSTGRES_PASSWORD: root
#      POSTGRES_DB: test_db
    ports:
      - "49150:5432"

  pgadmin:
    container_name: pgadmin4_ct
    image: dpage/pgadmin4
    # restart: always
    volumes:
      - pgadmin_value:/var/lib/pgadmin
    env_file:
      - .env.docker
    ports:
      - "5050:80"

volumes:
  db_value:
  pgadmin_value:

# docker-compose up -d
# connect PG admin -> http://localhost:5050
# Login:
# email -> pgadmin4@pgadmin:
# password -> admin
# Add New server
# Host -> host.docker.internal
# Port -> 49150
# USERNAME -> postgres
# PASSWORD -> docker
