version: '3.8'
services:
  db:
    image: postgres:13.0-alpine
    # restart: always
    volumes:
      - db_value:/var/lib/postgresql/data/
    env_file:
      - ../.env

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    # restart: always
    volumes:
      - static_value:/app/static/
      - media_value:/app/media/
    depends_on:
      - db
    env_file:
      - ../.env

volumes:
  db_value:
  static_value:
  media_value: