# Generated by Django 3.2.13 on 2022-10-04 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Baking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название десерта')),
                ('description', models.TextField(verbose_name='Описание и рецепт десерта')),
                ('image', models.ImageField(upload_to='baking_bot/images', verbose_name='Изображение десерта')),
            ],
            options={
                'verbose_name': 'Десерт',
                'verbose_name_plural': 'Десерты',
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='BakingType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100, unique=True, verbose_name='Тип десерта')),
            ],
            options={
                'verbose_name': 'Тип десерта',
                'verbose_name_plural': 'Типы десертов',
                'ordering': ('type',),
            },
        ),
        migrations.CreateModel(
            name='SimpleText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок команды')),
                ('description', models.TextField(verbose_name='Описание команды')),
            ],
            options={
                'verbose_name': 'Команда для бота',
                'verbose_name_plural': 'Команды для бота',
                'ordering': ('id',),
            },
        ),
        migrations.AddConstraint(
            model_name='simpletext',
            constraint=models.UniqueConstraint(fields=('title', 'description'), name='uniq_answer'),
        ),
        migrations.AddField(
            model_name='baking',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='baking', to='baking_bot.bakingtype', verbose_name='Тип десерта'),
        ),
        migrations.AddConstraint(
            model_name='baking',
            constraint=models.UniqueConstraint(fields=('title', 'description'), name='uniq_baking'),
        ),
    ]
