# Generated by Django 3.2.13 on 2022-09-17 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baking_bot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BakingType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100, unique=True, verbose_name='Тип выпечки')),
            ],
            options={
                'verbose_name': 'Тип выпечки',
                'verbose_name_plural': 'Типы выпечки',
                'ordering': ('type',),
            },
        ),
        migrations.AlterModelOptions(
            name='simpletext',
            options={'ordering': ('id',), 'verbose_name': 'Команда для бота', 'verbose_name_plural': 'Команды для бота'},
        ),
        migrations.AlterField(
            model_name='simpletext',
            name='text',
            field=models.TextField(verbose_name='Текс команды'),
        ),
        migrations.AlterField(
            model_name='simpletext',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Заголовок команды'),
        ),
        migrations.CreateModel(
            name='Baking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название выпечки')),
                ('description', models.TextField(verbose_name='Описание выпечки')),
                ('image', models.ImageField(upload_to='baking_bot/images', verbose_name='Изображение выпечки')),
                ('type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='baking', to='baking_bot.bakingtype', verbose_name='Тип выпечки')),
            ],
            options={
                'verbose_name': 'Выпечка',
                'verbose_name_plural': 'Выпечки',
                'ordering': ('title',),
            },
        ),
        migrations.AddConstraint(
            model_name='baking',
            constraint=models.UniqueConstraint(fields=('title', 'description'), name='uniq_baking'),
        ),
    ]
