# Generated by Django 3.2.13 on 2022-09-26 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baking_bot', '0003_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
