# Generated by Django 3.2.13 on 2022-09-29 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baking_bot', '0004_delete_image'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='simpletext',
            name='uniq_answer',
        ),
        migrations.RemoveField(
            model_name='simpletext',
            name='text',
        ),
        migrations.AddField(
            model_name='simpletext',
            name='description',
            field=models.TextField(default='zero text', verbose_name='Описание команды'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='baking',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AddConstraint(
            model_name='simpletext',
            constraint=models.UniqueConstraint(fields=('title', 'description'), name='uniq_answer'),
        ),
    ]
