# Generated by Django 3.2.13 on 2022-09-29 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baking_bot', '0005_auto_20220929_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baking',
            name='description',
            field=models.TextField(verbose_name='Описание и рецепт выпечки'),
        ),
    ]
